import jsPDF from 'jspdf'
import 'jspdf-autotable'

export function generateWorkflowReport(task: any, logs: any[], clientName: string) {
  const doc = new jsPDF()
  
  // Header
  doc.setFillColor(24, 24, 27) // Dark gray
  doc.rect(0, 0, 210, 40, 'F')
  
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('Campaign Execution Report', 14, 20)
  
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(200, 200, 200)
  doc.text(`Client: ${clientName}`, 14, 28)
  doc.text(`Workflow: ${task.workflow_templates?.name || 'Backlink Campaign'}`, 14, 34)
  
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 150, 28)
  doc.text(`Status: ${task.status.toUpperCase()}`, 150, 34)

  // Status section
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Execution Summary', 14, 55)
  
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('This document provides a summary of the actions taken by the AI agent during the workflow execution.', 14, 62)

  // Parse logs for actions
  let currentY = 75

  logs.forEach((log) => {
    if (currentY > 260) {
      doc.addPage()
      currentY = 20
    }

    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(63, 63, 70) // Zinc 700
    doc.text(`Step ${log.step_index + 1}: ${log.metadata?.step_name || 'Action'}`, 14, currentY)
    
    currentY += 6

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(100, 100, 100)
    
    // Split long messages
    const textLines = doc.splitTextToSize(log.message, 180)
    doc.text(textLines, 14, currentY)
    
    currentY += textLines.length * 4 + 8
  })

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Generated by Agentic SEO Platform - Page ${i} of ${pageCount}`, 14, 290)
  }

  doc.save(`${clientName.replace(/\s+/g, '_')}_Workflow_Report.pdf`)
}
